### ISSUE TITLE
SelectInput does not have 'initial' or 'placeholder' options.

### ISSUE THREAD

**Issue by snowman2** [tethysplatform/tethys#171]
The 'initial' and 'placeholder' attributes are missing in the SelectInput gizmo. They work fine when using the dictionary, but are not in the gizmo class.

**Comment by ezrajrice** [comment]
Alan,
Are you using the dev version? I have pushed this correction. There is not
a 'placeholder' attribute for SelectInput but there is an 'initial'
attribute in the dev branch. It is listed in the gizmo class as a list in
order to accomodate multiple initial selections. If there is a more
specific issue, I would love to see an example of what you are referring to.
Thanks,
Ezra

**Comment by swainn** [comment]
The initial attribute has been added to the Gizmo class, but place holder is still missing.

**Comment by swainn** [comment]
@snowman2 I know this is old, but I don't know if it makes sense to have a placeholder for a select gizmo. Can you name a use case?
